### ISSUE TITLE
Translate the README.md

### ISSUE THREAD

**Issue by ilovelinux** [CamTosh/Ethereum#7]
Hi!
Your project seems very good! I haven't tried it yet but I will do it as soon as I can!
But...You wrote readme.md in French and this could be a problem for non-french newbies :/
Fix it soon!

**Comment by CamTosh** [comment]
Hi,
Thanks, I can try to translate the readme.md in english, but i'm an english newbie :/

Can you help me for translation ?

**Comment by ilovelinux** [comment]
Yeah, sure! I'll help you!

If you wanna learn English you can use [Duolingo](https://www.duolingo.com/). My nickname is the same if you wanna add me to your Friends😄

**Comment by ilovelinux** [comment]
Hey!
I readed the readme. I think that we can remove  [Mémo](https://github.com/CamTosh/Ethereum/blob/master/readme.md#m%C3%A9mo) paragraph. A redirect to Geth/Ethminer github pages/websites is enough. Maybe we can let part where it's explained how to run Geth/Ethminer in order to enable the rpc connection. This: 
`λ Geth --rpc--rpcaddr ipDuServeurGeth --rpcport 8008 console`
`λ ethminer -G --opencl-device 0,1,2,3 --no-precompute -F ipDuServeurGeth:8008`

Also the [Overclock](https://github.com/CamTosh/Ethereum/blob/master/readme.md#overclock) paragraph doesn't seems inherent to the repo. Remember that this software isn't a mining software but just a dashboard for mining softwares.
Let me know what I have to do :)

**Comment by CamTosh** [comment]
Hey !

You right !

**Comment by ilovelinux** [comment]
#8
